### ISSUE TITLE
There is a new test fail caused by this change, tests must be updated too.

### ISSUE THREAD

**Issue by iloveeclipse** [eclipse-equinox/equinox.bundles#16]
There is a new test fail caused by this change, tests must be updated too.

https://download.eclipse.org/eclipse/downloads/drops4/I20220414-1800/testresults/html/org.eclipse.core.tests.runtime_ep424I-unit-cen64-gtk3-java11_linux.gtk.x86_64_11.html

```
org.eclipse.core.tests.internal.preferences.EclipsePreferencesTest | testLegacy | Failure | 
3.0 expected:<value.1649981901638-0.3893493642818254> but was:<null>junit.framework.ComparisonFailure: 3.0 expected:<value.1649981901638-0.3893493642818254> but was:<null>at junit.framework.Assert.assertEquals(Assert.java:100)at junit.framework.TestCase.assertEquals(TestCase.java:253)at org.eclipse.core.tests.internal.preferences.EclipsePreferencesTest.testLegacy(EclipsePreferencesTest.java:1091)at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
```

_Originally posted by @iloveeclipse in https://github.com/eclipse-equinox/equinox.bundles/issues/15#issuecomment-1100284364_

**Comment by iloveeclipse** [comment]
I was told, issues on github can be moved from one repo to another.
I can't move that one to eclipse-platform/eclipse.platform.runtime

**Comment by HannesWell** [comment]
> I was told, issues on github can be moved from one repo to another. I can't move that one to eclipse-platform/eclipse.platform.runtime

It looks like issues can only be transfered between repositories within the same organization (I didn't knew this restriction either):

https://docs.github.com/en/issues/tracking-your-work-with-issues/transferring-an-issue-to-another-repository
```
Note: You can only transfer issues between repositories owned by the same user or organization account. A private repository issue cannot be transferred to a public repository.
```

To bad. It looks like we can only recreate and mention an issue if it actually belongs to another organization.
