### ISSUE TITLE
-Dosgi.dataAreaRequiresExplicitInit=true doesn't work anymore

### ISSUE THREAD

**Issue by iloveeclipse** [eclipse-equinox/equinox.bundles#21]
While reviewing https://github.com/eclipse-platform/eclipse.platform.resources/pull/71 I've found, that I'm able to silently init a workspace (with default value) without specifying workspace location explicitly via prompt or `-data` argument, even if `-Dosgi.dataAreaRequiresExplicitInit=true` is set in eclipse.ini.

This is a regression, so bug https://bugs.eclipse.org/bugs/show_bug.cgi?id=514333 is back.

I'm investigating where it was broken... 4.19 is OK, 4.20 is broken...

OK, regression is coming from 
- bug https://bugs.eclipse.org/bugs/show_bug.cgi?id=572128 
- patch https://git.eclipse.org/r/c/platform/eclipse.platform.resources/+/178144 
- commit https://github.com/eclipse-platform/eclipse.platform.resources/commit/a8a8d824145ea1f309eb0b4ade83995544eead50

Ironically, commit message was `The start code for the plugin can be migrated to run inside Workspace
without changing existing behaviour.`...

**Comment by tjwatson** [comment]
It seems we don't have tests for this?

**Comment by iloveeclipse** [comment]
Yes, we don't have tests. If you have a pointer how a test could be added that tests Eclipse startup with some custom launch arguments and checks something from inside that Eclipse, I could add one.

**Comment by tjwatson** [comment]
> Yes, we don't have tests. If you have a pointer how a test could be added that tests Eclipse startup with some custom launch arguments and checks something from inside that Eclipse, I could add one.

There is something called session tests that can be run.  It is not the most elegant way of testing but it can be done.  Here is one of the more "simple" testcases I found that uses it where the testcase is setting some specific values in a config.ini: [org.eclipse.osgi.tests.configuration.EclipseStarterConfigIniTest](https://github.com/eclipse-equinox/equinox.framework/blob/ff3cec53a2285bbc64a5a5cc483b5c6e78abe17c/bundles/org.eclipse.osgi.tests/src/org/eclipse/osgi/tests/configuration/EclipseStarterConfigIniTest.java#L28)

**Comment by iloveeclipse** [comment]
OK, I have a fix but that is in resources, so I will close this issue and reopen one in platform resources.

**Comment by iloveeclipse** [comment]
Proposed fix: https://github.com/eclipse-platform/eclipse.platform.runtime/pull/36
