### ISSUE TITLE
Build failure in 4.24 I-Build: I20220428-0120

### ISSUE THREAD

**Issue by sravanlakkimsetti** [eclipse-equinox/equinox.bundles#32]
Error message 

```
 [ERROR] Failed to execute goal org.eclipse.tycho:tycho-compiler-plugin:3.0.0-SNAPSHOT:compile (default-compile) on project org.eclipse.equinox.log.stream: Compilation failure: Compilation failure: 
 [ERROR] /home/jenkins/agent/workspace/I-build-4.24/eclipse.platform.releng.aggregator/eclipse.platform.releng.aggregator/cje-production/gitCache/eclipse.platform.releng.aggregator/rt.equinox.bundles/bundles/org.eclipse.equinox.log.stream/src/org/eclipse/equinox/internal/log/stream/LogStreamProviderFactory.java: 
 [ERROR] 	/*******************************************************************************
 [ERROR] 	^
 [ERROR] The type org.osgi.util.function.Predicate cannot be resolved. It is indirectly referenced from required .class files
 [ERROR] 1 problem (1 error)
 [ERROR] -> [Help 1]
 [ERROR] 
 [ERROR] To see the full stack trace of the errors, re-run Maven with the -e switch.
 [ERROR] Re-run Maven using the -X switch to enable full debug logging.
 [ERROR] 
 [ERROR] For more information about the errors and possible solutions, please read the following articles:
 [ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/MojoFailureException
 [ERROR] 
 [ERROR] After correcting the problems, you can resume the build with the command
 [ERROR]   mvn <args> -rf :org.eclipse.equinox.log.stream
```

**Comment by HannesWell** [comment]
PR #31 hopefully fixes that.

**Comment by HannesWell** [comment]
PR #31 is submitted.
@sravanlakkimsetti could you please restart the I-build.

**Comment by sravanlakkimsetti** [comment]
> PR #31 is submitted. @sravanlakkimsetti could you please restart the I-build.

restarted the build

**Comment by akurtakov** [comment]
Build succeeded

**Comment by HannesWell** [comment]
This is hopefully a fix of the error:

https://github.com/eclipse-equinox/equinox.bundles/pull/31
 

Gesendet: Donnerstag, 28. April 2022 um 08:31 Uhr
Von: "Sravan Kumar Lakkimsetti" ***@***.***>
An: "eclipse-equinox/equinox.bundles" ***@***.***>
Cc: "Subscribed" ***@***.***>
Betreff: [eclipse-equinox/equinox.bundles] Build failure in 4.24 I-Build: I20220428-0120 (Issue #32)


 

Error message

[ERROR] Failed to execute goal org.eclipse.tycho:tycho-compiler-plugin:3.0.0-SNAPSHOT:compile (default-compile) on project org.eclipse.equinox.log.stream: Compilation failure: Compilation failure: [ERROR] /home/jenkins/agent/workspace/I-build-4.24/eclipse.platform.releng.aggregator/eclipse.platform.releng.aggregator/cje-production/gitCache/eclipse.platform.releng.aggregator/rt.equinox.bundles/bundles/org.eclipse.equinox.log.stream/src/org/eclipse/equinox/internal/log/stream/LogStreamProviderFactory.java: [ERROR] /******************************************************************************* [ERROR] ^ [ERROR] The type org.osgi.util.function.Predicate cannot be resolved. It is indirectly referenced from required .class files [ERROR] 1 problem (1 error) [ERROR] -> [Help 1] [ERROR] [ERROR] To see the full stack trace of the errors, re-run Maven with the -e switch. [ERROR] Re-run Maven using the -X switch to enable full debug logging. [ERROR] [ERROR] For more information about the errors and possible solutions, please read the following articles: [ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/MojoFailureException [ERROR] [ERROR] After correcting the problems, you can resume the build with the command [ERROR] mvn <args> -rf :org.eclipse.equinox.log.stream
