### ISSUE TITLE
org.eclipse.equinox.preferences has wrong version

### ISSUE THREAD

**Issue by iloveeclipse** [eclipse-equinox/equinox.bundles#35]
The version of org.eclipse.equinox.preferences is most likely wrong after https://github.com/eclipse-equinox/equinox.bundles/pull/25. 

3.9 version was released already, we can't add API with old version numbers.

I see that API filters were added, because API tooling wants to increase **major** bundle version, but this doesn't mean if we don't increase major we won't increase minor segment.

This causes such errors like https://github.com/eclipse-platform/eclipse.platform.resources/issues/102#issuecomment-1112987841

Because client code that receives this API re-exported via org.eclipse.core.runtime doesn't see new fields added if the installation contains "old" 3.9 bundles without this API.

So I think we must:
1) bump org.eclipse.equinox.preferences to 3.10 here : https://github.com/eclipse-equinox/equinox.bundles/blob/f3c4cedb47cf2cfc007b55161f1954fd01d55551/bundles/org.eclipse.equinox.preferences/META-INF/MANIFEST.MF#L5
2) also bump version **of the package** (see manifest that says it has 3.4.0 version: https://github.com/eclipse-equinox/equinox.bundles/blob/f3c4cedb47cf2cfc007b55161f1954fd01d55551/bundles/org.eclipse.equinox.preferences/META-INF/MANIFEST.MF#L13) 
3) bump re-exported package in org.eclipse.core.runtime to 3.10 here https://github.com/eclipse-platform/eclipse.platform.runtime/blob/4cc1d01f2d8f2e9494b69003f05e064683ebc7cd/bundles/org.eclipse.core.runtime/META-INF/MANIFEST.MF#L16

_Originally posted by @iloveeclipse in https://github.com/eclipse-equinox/equinox.bundles/pull/25#discussion_r862459141_

**Comment by laeubi** [comment]
Thanks for you detailed description, I must confess API tools are a mystery for me, sometimes I get no complains at all but the build fails, then it suggest to increase versions while the build complains it should not.
In this case, if I adjust the version I get a marker in the manifest:

> Description	Resource	Path	Location	Type
> The minor version should be the same for version 3.10.0, since no new APIs have been added since version 3.9.100	MANIFEST.MF	/org.eclipse.equinox.preferences/META-INF	line 5	Version Numbering Problem

Can I simply ignore this?

**Comment by iloveeclipse** [comment]
@mickaelistria : See bug description, there is more work to be done.

**Comment by mickaelistria** [comment]
I actually didn't close it explicitly, it's because I linked a PR, which got closed, that this issue was closed.

**Comment by laeubi** [comment]
@iloveeclipse I think we need to wait for the next ibuild to "bubble up" this change for the individual bundles build? Also as these changes are out of this repository it might be better to have dedicated issues in the corresponding repro to track this.

**Comment by iloveeclipse** [comment]
@laeubi : 
1) you can prepare right PR already, locally you should be able to see if API tooling will complain etc.
2) Sure, feel free to create dedicated issue for platform UI & eventually platform resources and address the remaining points there. 
3) As long as 1) and 2) aren't done, this issue should remain open.

**Comment by laeubi** [comment]
created https://github.com/eclipse-platform/eclipse.platform.runtime/pull/48 this could be closed then.
