### ISSUE TITLE
Storage location for ConfigAdmin

### ISSUE THREAD

**Issue by fipro78** [eclipse-equinox/equinox.bundles#44]
Hi,

I created a small OSGi application based on Equinox. I then created a small JVM using Atomos and jlink. It works quite nice, but it seems the configuration I apply at runtime is not persisted.

I had the same issue with a similar setup using the Felix bundles. I ended up adding 

`-Dfelix.cm.dir="<CONFIG_PERSISTENCE_FOLDER>"`

to the start script JLINK_VM_OPTIONS. For the Felix jlink JVM this works fine and the folder is created with the persisted configuration.

But I am not able to do this for the Equinox ConfigAdmin. Looking at the ConfigurationStore it seems to always use the BundleContext and does not support any other configuration. I then thought to set the configuration area via

`-Dosgi.configuration.area="<CONFIG_PERSISTENCE_FOLDER>"`

but that doesn't have any effect.

Is there any way to specify the location where the configuration should be persisted? Should it be osgi.configuration.area to specify the whole configuration folder and bundle cache? Or is there another system property I haven't found yet?

**Comment by fipro78** [comment]
No, I am bundling my executable jar using bndtools and then create the jlink image. No such options.

**Comment by laeubi** [comment]
Ah I missed that you package it in a special way. Equinox uses the "persistent storage area provided for the bundle by the framework" (see org.eclipse.equinox.internal.cm.ConfigurationStore.ConfigurationStore(ConfigurationAdminFactory, BundleContext)) that is if your Framework does not support such an area (what is optional) it won't persist anything.

I always used felix fileinstall in standalone applications as it allows to read and write back configurations and you are not bound to the specific storage mechanism of the underlying CM service.

**Comment by laeubi** [comment]
By the way I think its won't be hard to add support for something like `-Dequinos.cm.dir=...` if you take a look at the code, so I think contributions are welcome :-)

**Comment by tjwatson** [comment]
Are you saying that the framework is not correctly persisting the bundle data area from one launch of Atomos to the next?  If you have steps to reproduce that may clear things up.

**Comment by rotty3000** [comment]
Have you tried either of these run instructions?

-runkeep – Keep the framework working directory. That is, do not clean at start up
-runstorage – The working directory
